spring:
  profiles:
    active: local
---
spring:
  profiles: local

  datasource:
    url: jdbc:mariadb://localhost:3306/yolo
    driver-class-name: org.mariadb.jdbc.Driver
    username: junyoung
    password: wnsdud@123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
#   org.hibernate.type: trace
