spring:
  profiles:
    active: local
---
spring:
  profiles: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/yolo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show-sql: false
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
