spring:
  security:
    oauth2:
      client:
        registration:
         google:
           client-id: "671594200442-i753hs7b0kub7pjsdrvggple6stoio06.apps.googleusercontent.com"
           client-secret: "Zp8xwRq1n8dS5nnE1oYIb_br"
           scope:
             - profile
             - email
