spring:
  profiles:
    active: mysql
  batch:
    job:
      names: ${job.name:NONE}
logging:
  level:
    org:
      springframework:
        batch: DEBUG
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/yolo
      username: sa
      password:
      driver-class-name: org.h2.Driver

jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  open-in-view: false
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      #        show_sql: true
      format_sql: true
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mariadb://localhost:3306/yolo
    driver-class-name: org.mariadb.jdbc.Driver
    username: junyoung
    password: wnsdud@123
jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  open-in-view: false
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      #        show_sql: true
      format_sql: true
